[project]
authors = ["pablovela5620 <pablovela5620@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "MASt3R-SLAM"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.6"

[tasks]
_install-lietorch = { cmd = "python -m pip install git+https://github.com/Dhuldhoyavarun/lietorch.git@cu126", outputs = [
    ".pixi/envs/default/lib/python3.11/site-packages/lietorch/__init__.py",
] }




_install-mast3r = { cmd = "python -m pip install -e thirdparty/mast3r", outputs = [
    "thirdparty/mast3r/MAST3R.egg-info",
] }
install = { cmd = "python -m pip install --no-build-isolation -e . ", depends-on = [
    "_install-lietorch",

    "_install-mast3r",
    "_download-checkpoints",
    "_download-example-data",
], outputs = [
    "mast3r_slam_backends.cpython-311-x86_64-linux-gnu.so",
], description = "Building Kernels and Installing, this could take a while..." }

app = { cmd = "python tools/gradio-app.py", depends-on = [
    "install",
], description = "Run Gradio App" }
example-base = { cmd = "python tools/mast3r_slam_inference.py --dataset data/normal-apt-tour.MOV --img-size 512 --config config/base.yaml", depends-on = [
    "install",
], description = "Running Inference on Example Data using 512 image size and base config" }
example-fast = { cmd = "python tools/mast3r_slam_inference.py --dataset data/normal-apt-tour.MOV --img-size 224 --config config/fast.yaml", depends-on = [
    "install",
], description = "Running Inference on Example Data using 224 image size and fast config" }

[tasks._download-checkpoints]
cmd = """
    test -e checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth
    || (
        huggingface-cli download pablovela5620/mast3r-slam \
        MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric_retrieval_codebook.pkl MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric_retrieval_trainingfree.pth --repo-type model \
        --local-dir checkpoints/
    )
"""

[tasks._download-example-data]
cmd = """
    test -e data/normal-apt-tour.MOV
    || (
        huggingface-cli download pablovela5620/mast3r-slam-example-data \
        normal-apt-tour.MOV --repo-type dataset \
        --local-dir data/
    )
"""

outputs = ["data/normal-apt-tour.MOV"]
description = "Downloads Example Data"

[pypi-dependencies]
torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = "==0.22.1", index = "https://download.pytorch.org/whl/cu126" }
# torchcodec = { version = "==0.2.0", index = "https://download.pytorch.org/whl/cu126" }
simplecv = { git = "https://github.com/pablovela5620/simplecv.git", tag="v0.4.0" }
# lietorch = { url = "https://huggingface.co/datasets/pablovela5620/mast3r-slam-whls/resolve/main/lietorch-0.2-cp311-cp311-linux_x86_64.whl" }
gradio-rerun = { url = "https://huggingface.co/datasets/pablovela5620/gradio-rr-wheels/resolve/main/gradio_rerun-0.0.11-py3-none-any.whl" }

[dependencies]
python = "3.11.*"
numpy = "<2"
cuda-nvcc = "12.6.*"
cuda-version = "12.6.*"
ffmpeg = ">=7.1.0,<8"
pip = ">=25.0.1,<26"
tyro = ">=0.9.1,<0.10"
rerun-sdk = ">=0.22.0,<0.23"
beartype = ">=0.20.0,<0.21"
jaxtyping = ">=0.2.36,<0.3"
eigen = ">=3.4.0,<4"
gradio = "<5"
py-opencv = ">=4.11.0,<5"
pyserde = ">=0.23.0,<0.24"
open3d = ">=0.19.0,<0.20"
